CREATE SCHEMA Quiz2;
use Quiz2;
-- a)
CREATE TABLE Product(
    PT_MAKER VARCHAR(50) NOT NULL,
    MODEL VARCHAR(30) PRIMARY KEY,
    PT_TYPE CHAR(10) NOT NULL
);
-- b)
CREATE TABLE PC(
    MODEL VARCHAR(30) PRIMARY KEY,
    PC_SPEED CHAR(20) NOT NULL,
    PC_RAM CHAR(20) NOT NULL,
    PC_HD double NOT NULL,
    PC_PRICE double NOT NULL,
    FOREIGN KEY (MODEL) REFERENCES Product(MODEL)
);
-- c)
CREATE TABLE Laptop(
    MODEL VARCHAR(30) PRIMARY KEY,
    LP_SPEED CHAR(20) NOT NULL,
    LP_RAM CHAR(20) NOT NULL,
    LP_HD double NOT NULL,
    LP_SCREEN double NOT NULL,
    LP_PRICE double NOT NULL,
    FOREIGN KEY (MODEL) REFERENCES Product(MODEL)
);
-- d)
CREATE TABLE Printer(
    MODEL VARCHAR(30) PRIMARY KEY,
    PR_COLOR CHAR(20) NOT NULL,
    PR_TYPE CHAR(10) NOT NULL,
    PR_PRICE double NOT NULL,
    FOREIGN KEY (MODEL) REFERENCES Product(MODEL)
);
-- e)
ALTER TABLE Printer DROP PR_COLOR;
-- f)
ALTER TABLE Laptop ADD LP_RegisterDate DATE;
-- g)
SELECT * FROM Laptop WHERE MODEL LIKE 'ThinkPad';
-- h)
SELECT * FROM Laptop WHERE LP_HD > 100;

SELECT PT_MAKER
FROM Product,
     (
         SELECT * FROM Laptop WHERE LP_HD > 100.0
     ) AS LaptopData
WHERE Product.MODEL = LaptopData.MODEL;